-- Agentic Travel Planner - MySQL 8 schema
-- Generated by scripts/export_schema.py from app/models.py. The backend also
-- creates these tables automatically on startup, so running this file is optional.
-- Run it once against an empty database (CREATE INDEX is not idempotent in MySQL).
--
--   mysql -u root -p < schema.sql
--   python -m app.seed          # load the mock flight/hotel inventory

CREATE DATABASE IF NOT EXISTS travel_planner CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE travel_planner;

CREATE TABLE IF NOT EXISTS airlines (
	code VARCHAR(3) NOT NULL,
	name VARCHAR(80) NOT NULL,
	hub VARCHAR(3) NOT NULL,
	rating FLOAT NOT NULL,
	PRIMARY KEY (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS airports (
	iata VARCHAR(3) NOT NULL,
	name VARCHAR(120) NOT NULL,
	city VARCHAR(80) NOT NULL,
	country VARCHAR(80) NOT NULL,
	country_code VARCHAR(2) NOT NULL,
	region VARCHAR(40) NOT NULL,
	latitude FLOAT NOT NULL,
	longitude FLOAT NOT NULL,
	timezone VARCHAR(64) NOT NULL,
	currency VARCHAR(3) NOT NULL,
	language VARCHAR(60) NOT NULL,
	cost_index FLOAT NOT NULL,
	neighborhoods JSON NOT NULL,
	PRIMARY KEY (iata)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX ix_airports_city ON airports (city);

CREATE TABLE IF NOT EXISTS offer_snapshots (
	id VARCHAR(100) NOT NULL,
	kind VARCHAR(10) NOT NULL,
	provider VARCHAR(20) NOT NULL,
	payload JSON NOT NULL,
	created_at DATETIME NOT NULL,
	expires_at DATETIME NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
	id INTEGER NOT NULL AUTO_INCREMENT,
	email VARCHAR(190) NOT NULL,
	name VARCHAR(120) NOT NULL,
	created_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS flight_schedules (
	id INTEGER NOT NULL AUTO_INCREMENT,
	flight_number VARCHAR(8) NOT NULL,
	airline_code VARCHAR(3) NOT NULL,
	origin VARCHAR(3) NOT NULL,
	destination VARCHAR(3) NOT NULL,
	departure_time VARCHAR(5) NOT NULL,
	duration_minutes INTEGER NOT NULL,
	stops INTEGER NOT NULL,
	via VARCHAR(3),
	aircraft VARCHAR(40) NOT NULL,
	days_of_week VARCHAR(7) NOT NULL,
	base_fare NUMERIC(10, 2) NOT NULL,
	seats_economy INTEGER NOT NULL,
	seats_premium_economy INTEGER NOT NULL,
	seats_business INTEGER NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (flight_number),
	FOREIGN KEY(airline_code) REFERENCES airlines (code),
	FOREIGN KEY(origin) REFERENCES airports (iata),
	FOREIGN KEY(destination) REFERENCES airports (iata)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX ix_schedule_route ON flight_schedules (origin, destination);

CREATE TABLE IF NOT EXISTS hotels (
	id INTEGER NOT NULL AUTO_INCREMENT,
	code VARCHAR(16) NOT NULL,
	name VARCHAR(120) NOT NULL,
	city_code VARCHAR(3) NOT NULL,
	neighborhood VARCHAR(80) NOT NULL,
	address VARCHAR(200) NOT NULL,
	stars INTEGER NOT NULL,
	rating FLOAT NOT NULL,
	review_count INTEGER NOT NULL,
	base_rate NUMERIC(10, 2) NOT NULL,
	amenities JSON NOT NULL,
	room_types JSON NOT NULL,
	description TEXT NOT NULL,
	free_cancellation BOOL NOT NULL,
	breakfast_included BOOL NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (code),
	FOREIGN KEY(city_code) REFERENCES airports (iata)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX ix_hotels_city_code ON hotels (city_code);

CREATE TABLE IF NOT EXISTS trips (
	id INTEGER NOT NULL AUTO_INCREMENT,
	user_id INTEGER NOT NULL,
	title VARCHAR(200) NOT NULL,
	origin VARCHAR(3) NOT NULL,
	destinations JSON NOT NULL,
	start_date DATE NOT NULL,
	end_date DATE NOT NULL,
	adults INTEGER NOT NULL,
	children INTEGER NOT NULL,
	budget NUMERIC(12, 2) NOT NULL,
	currency VARCHAR(3) NOT NULL,
	cabin_class VARCHAR(20) NOT NULL,
	hotel_min_stars INTEGER NOT NULL,
	pace VARCHAR(20) NOT NULL,
	travel_style VARCHAR(30) NOT NULL,
	interests JSON NOT NULL,
	dietary_needs VARCHAR(300),
	accessibility_needs VARCHAR(300),
	notes TEXT,
	status VARCHAR(20) NOT NULL,
	current_step VARCHAR(80),
	error TEXT,
	plan JSON,
	plan_version INTEGER NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	completed_at DATETIME,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX ix_trips_status ON trips (status);
CREATE INDEX ix_trips_user_id ON trips (user_id);

CREATE TABLE IF NOT EXISTS bookings (
	id INTEGER NOT NULL AUTO_INCREMENT,
	reference VARCHAR(12) NOT NULL,
	user_id INTEGER NOT NULL,
	trip_id INTEGER,
	kind VARCHAR(10) NOT NULL,
	provider VARCHAR(20) NOT NULL,
	status VARCHAR(20) NOT NULL,
	offer_id VARCHAR(100) NOT NULL,
	summary VARCHAR(255) NOT NULL,
	details JSON NOT NULL,
	total_price NUMERIC(12, 2) NOT NULL,
	currency VARCHAR(3) NOT NULL,
	refund_amount NUMERIC(12, 2),
	contact_email VARCHAR(190) NOT NULL,
	contact_phone VARCHAR(40),
	flight_number VARCHAR(8),
	travel_date DATE,
	cabin_class VARCHAR(20),
	seats INTEGER NOT NULL,
	hotel_code VARCHAR(16),
	room_type VARCHAR(10),
	check_in DATE,
	check_out DATE,
	rooms INTEGER NOT NULL,
	created_at DATETIME NOT NULL,
	cancelled_at DATETIME,
	PRIMARY KEY (id),
	UNIQUE (reference),
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE,
	FOREIGN KEY(trip_id) REFERENCES trips (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX ix_booking_flight_inventory ON bookings (flight_number, travel_date, cabin_class, status);
CREATE INDEX ix_booking_hotel_inventory ON bookings (hotel_code, room_type, status);
CREATE INDEX ix_bookings_user_id ON bookings (user_id);

CREATE TABLE IF NOT EXISTS trip_events (
	id INTEGER NOT NULL AUTO_INCREMENT,
	trip_id INTEGER NOT NULL,
	seq INTEGER NOT NULL,
	agent VARCHAR(60),
	kind VARCHAR(30) NOT NULL,
	message TEXT NOT NULL,
	created_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_trip_event_seq UNIQUE (trip_id, seq),
	FOREIGN KEY(trip_id) REFERENCES trips (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX ix_trip_events_trip_id ON trip_events (trip_id);

CREATE TABLE IF NOT EXISTS trip_messages (
	id INTEGER NOT NULL AUTO_INCREMENT,
	trip_id INTEGER NOT NULL,
	`role` VARCHAR(20) NOT NULL,
	content TEXT NOT NULL,
	changes JSON NOT NULL,
	created_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(trip_id) REFERENCES trips (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX ix_trip_messages_trip_id ON trip_messages (trip_id);

CREATE TABLE IF NOT EXISTS booking_travelers (
	id INTEGER NOT NULL AUTO_INCREMENT,
	booking_id INTEGER NOT NULL,
	first_name VARCHAR(80) NOT NULL,
	last_name VARCHAR(80) NOT NULL,
	traveler_type VARCHAR(10) NOT NULL,
	date_of_birth DATE,
	ticket_number VARCHAR(20),
	PRIMARY KEY (id),
	FOREIGN KEY(booking_id) REFERENCES bookings (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX ix_booking_travelers_booking_id ON booking_travelers (booking_id);
