"""Regenerate ``schema.sql`` (MySQL 8 DDL) from the SQLAlchemy models.

    python scripts/export_schema.py > schema.sql
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from sqlalchemy.dialects import mysql  # noqa: E402
from sqlalchemy.schema import CreateIndex, CreateTable  # noqa: E402

from app import models  # noqa: E402,F401
from app.db import Base  # noqa: E402

HEADER = """-- Agentic Travel Planner - MySQL 8 schema
-- Generated by scripts/export_schema.py from app/models.py. The backend also
-- creates these tables automatically on startup, so running this file is optional.
-- Run it once against an empty database (CREATE INDEX is not idempotent in MySQL).
--
--   mysql -u root -p < schema.sql
--   python -m app.seed          # load the mock flight/hotel inventory

CREATE DATABASE IF NOT EXISTS travel_planner CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE travel_planner;
"""


def main() -> None:
    dialect = mysql.dialect()
    out = [HEADER]
    for table in Base.metadata.sorted_tables:
        ddl = str(CreateTable(table).compile(dialect=dialect)).strip()
        ddl = ddl.replace("CREATE TABLE", "CREATE TABLE IF NOT EXISTS", 1)
        out.append(ddl + " ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;")
        for index in sorted(table.indexes, key=lambda i: i.name or ""):
            out.append(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";")
        out.append("")
    text = "\n".join(out)
    sys.stdout.write("\n".join(line.rstrip() for line in text.splitlines()) + "\n")


if __name__ == "__main__":
    main()
